# Generated by Django 4.0.6 on 2022-07-11 20:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=200)),
            ],
            options={
                'permissions': [('special_status', 'Can view farms')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('checks_ran', tinymce.models.HTMLField(blank=True, null=True)),
                ('recommendations', tinymce.models.HTMLField(blank=True, null=True)),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='queryObj.farm')),
            ],
        ),
    ]
